server:
  port: 8090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
spring:
  profiles:
    active: dev
  application:
    name: shop-goods
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8868,192.168.1.3:8858,192.168.1.3:8848
        service: ${spring.application.name}
#        namespace: eb21f7f0-48a6-4aa6-8930-89e959d34d5e
  mvc:
    static-path-pattern: classpath:/META-INF/static/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prod?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
